spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    org:
      hibernate:
  file:
    name: log.log
#        SQL: DEBUG
#        type: TRACE
